
SERIAL_PORT_NOT_CONNECTED_NAME = 'No Serial Ports Detected'

SHOW_PORT_DETAIL_SHORT = 0
SHOW_PORT_DETAIL_FULL = 1

HIDE_LIST = ["Standard Serial over Bluetooth link"]
SHOW_HIDDEN_PORTS_NO = 0
SHOW_HIDDEN_PORTS_YES = 1
